version: '3.7'
services:
  user-interaction:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:9.4
    ports:
      - "5433:5433"
    volumes:
      - type: volume
        source: dbdata
        target: "/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=password
  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - "9001:80"
    volumes:
      - type: volume
        source: pgadmindata
        target: "/var/lib/pgadmin"
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@test.com
      - PGADMIN_DEFAULT_PASSWORD=test
volumes:
  dbdata:
  pgadmindata:
